application: tweet-creep
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

handlers:
- url: /style
  static_dir: style

- url: /.*
  script: main.application

