application: tweet-creep
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

handlers:
- url: /css
  static_dir: static/css

- url: /static
  static_dir: static

- url: /static/img/
  static_files: static/img/
  upload: static/img/

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /.*
  script: main.application